import Head from 'next/head'
import Header from '../Components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'

export default function Home(props) {
  console.log(props.results)
  return (
    <div>
      <Head>
        <title>HULU 2.0 | Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Nav */}
      <Nav/>
      {/* Result */}
      <Results Movies={props.results}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const request = await fetch('https://api.themoviedb.org/3/trending/all/day?api_key=92ad5a933b9f93a0c1b49a8b2d907866').then((res)=>res.json())
  return {
    props: {
      results: request.results,
    }, // will be passed to the page component as props
  }
}