import Head from 'next/head'
import Header from '../Components/Header'
import Nav from '../components/Nav'
import AllMovie from '../components/AllMovie'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>HULU 2.0 | Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Nav */}
      {/* <Nav/> */}
      {/* Result */}
      <AllMovie Movies={props}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const nowplaying = await fetch('https://api.themoviedb.org/3/movie/now_playing?api_key=3fee6f3db8e1f60f373cb20f26be82a6&language=en-US&page=1').then((res)=>res.json())
  const latest = await fetch('https://api.themoviedb.org/3/movie/latest?api_key=3fee6f3db8e1f60f373cb20f26be82a6&language=en-US').then((res)=>res.json())
  const populer = await fetch('https://api.themoviedb.org/3/movie/popular?api_key=3fee6f3db8e1f60f373cb20f26be82a6&language=en-US&page=1').then((res)=>res.json())
  const trending = await fetch('https://api.themoviedb.org/3/trending/all/day?api_key=3fee6f3db8e1f60f373cb20f26be82a6').then((res)=>res.json())
  const toprated = await fetch('https://api.themoviedb.org/3/movie/top_rated?api_key=3fee6f3db8e1f60f373cb20f26be82a6&language=en-US&page=1').then((res)=>res.json())
  const upcoming = await fetch('https://api.themoviedb.org/3/movie/upcoming?api_key=3fee6f3db8e1f60f373cb20f26be82a6&language=en-US&page=1').then((res)=>res.json())

  return {
    props: {
      nowplaying,
      latest,
      populer,
      trending,
      toprated,
      upcoming
    }, 
  }
}